/* runloom_heavy_frames.h -- GENERATED by tools/heavy_frames/gen_heavy_frames.py.  Do not edit by hand.
 *
 * Python-visible symbols whose C implementation has an unusually fat SINGLE
 * stack frame (from the stdlib .eh_frame profile, 3.13.13t).
 * The cold-start optimizer bumps a goroutine's first-incarnation stack to
 * hold the fat frame when its code references one of these.  Sizes are the
 * largest fat frame in the symbol's module. */
#ifndef RUNLOOM_HEAVY_FRAMES_H
#define RUNLOOM_HEAVY_FRAMES_H
#include <stddef.h>

typedef struct { const char *sym; size_t frame_bytes; } runloom_heavy_frame_t;

static const runloom_heavy_frame_t runloom_heavy_frames[] = {
    {"Context", 262376},   /* _decimal */
    {"Decimal", 262376},   /* _decimal */
    {"getcontext", 262376},   /* _decimal */
    {"localcontext", 262376},   /* _decimal */
    {"setcontext", 262376},   /* _decimal */
    {"gethostbyaddr", 16664},   /* _socket */
    {"gethostbyname", 16664},   /* _socket */
    {"gethostbyname_ex", 16664},   /* _socket */
};
#define RUNLOOM_HEAVY_FRAME_COUNT ((int)(sizeof runloom_heavy_frames / sizeof runloom_heavy_frames[0]))

#endif /* RUNLOOM_HEAVY_FRAMES_H */
