#!/usr/bin/env python3
"""Generate src/runloom_c/runloom_heavy_frames.h from the stdlib C-frame profile.

The profile (stdlib_fat_frames.json, trimmed from a full DWARF .eh_frame scan of
the 3.13t stdlib C extensions) lists every C function whose SINGLE stack frame is
larger than 8 KiB.  A goroutine runs on a small C stack, so one of these fat
frames can overflow it in a single call -- the standout is _decimal's
`squaretrans_pow2` at 256 KiB (big-integer multiply/pow).

C function names are not Python-visible, so we map the fat-frame *modules* to the
Python API symbols that reach them (hand-maintained -- you can't derive
`Decimal` from `squaretrans_pow2`).  Only modules whose work can actually run on
a goroutine are included; startup/path helpers, the already-cooperative
`select`, the already-neutralised module-shadowing hint, and test-only functions
are deliberately left out.  The emitted size per symbol is the largest fat frame
in its module.

The runtime cold-start optimizer (runloom_stackadvice.c) scans an unseen
goroutine kind's bytecode names for these symbols and, if present, starts it big
enough to hold the fat frame -- so a Decimal-heavy goroutine does not overflow on
its very first run, before the auto-sizer has measured it.

Regenerate:  python3 tools/heavy_frames/gen_heavy_frames.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
PROFILE = os.path.join(HERE, "stdlib_fat_frames.json")
OUT = os.path.join(HERE, "..", "..", "src", "runloom_c", "runloom_heavy_frames.h")

# module -> Python-visible symbols that reach that module's fat C frames.
# Hand-maintained (C symbol -> Python API is not mechanically derivable).
MODULE_SYMBOLS = {
    "_decimal": ["Decimal", "getcontext", "localcontext", "setcontext", "Context"],
    "_socket":  ["gethostbyname", "gethostbyname_ex", "gethostbyaddr"],
}


def main():
    prof = json.load(open(PROFILE))
    # largest fat frame per module
    by_module = {}
    for f in prof["fat_frames_over_8k"]:
        m, b = f["module"], f["stack_bytes"]
        if b > by_module.get(m, 0):
            by_module[m] = b

    rows = []
    for module, syms in MODULE_SYMBOLS.items():
        bytes_ = by_module.get(module)
        if bytes_ is None:
            continue
        for sym in syms:
            rows.append((sym, bytes_, module))
    rows.sort(key=lambda r: (-r[1], r[0]))

    lines = []
    lines.append("/* runloom_heavy_frames.h -- GENERATED by "
                 "tools/heavy_frames/gen_heavy_frames.py.  Do not edit by hand.")
    lines.append(" *")
    lines.append(" * Python-visible symbols whose C implementation has an unusually fat SINGLE")
    lines.append(" * stack frame (from the stdlib .eh_frame profile, %s)."
                 % prof["meta"]["python"])
    lines.append(" * The cold-start optimizer bumps a goroutine's first-incarnation stack to")
    lines.append(" * hold the fat frame when its code references one of these.  Sizes are the")
    lines.append(" * largest fat frame in the symbol's module. */")
    lines.append("#ifndef RUNLOOM_HEAVY_FRAMES_H")
    lines.append("#define RUNLOOM_HEAVY_FRAMES_H")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append("typedef struct { const char *sym; size_t frame_bytes; } runloom_heavy_frame_t;")
    lines.append("")
    lines.append("static const runloom_heavy_frame_t runloom_heavy_frames[] = {")
    for sym, b, module in rows:
        lines.append('    {"%s", %d},   /* %s */' % (sym, b, module))
    lines.append("};")
    lines.append("#define RUNLOOM_HEAVY_FRAME_COUNT "
                 "((int)(sizeof runloom_heavy_frames / sizeof runloom_heavy_frames[0]))")
    lines.append("")
    lines.append("#endif /* RUNLOOM_HEAVY_FRAMES_H */")
    text = "\n".join(lines) + "\n"
    with open(os.path.normpath(OUT), "w") as f:
        f.write(text)
    print("wrote", os.path.normpath(OUT), "with", len(rows), "symbols")


if __name__ == "__main__":
    main()
