#!/usr/bin/env python3
"""gen_sweep.py -- synthesise the full memory_order lattice for the park/wake
store-buffering (SB / Dekker) shape, so herd7 finds the *weakest sufficient*
fence automatically instead of us hand-picking two endpoints.

verify/litmus/ ships two hand-written points of this shape:
  parkwake_no_fence.litmus  (release/acquire, no fence)   -> Sometimes (bug)
  parkwake_sc_fence.litmus  (release/acquire + seq_cst)   -> Never     (fix)

This generator fills in the whole lattice between them: it varies, symmetrically
on both threads, the store order {relaxed, release}, the load order {relaxed,
acquire}, and the inter-op fence {none, release, seq_cst} -- 2*2*3 = 12 variants.
Running them all through herd7 (run_sweep.sh) shows *exactly* which combinations
forbid the lost wakeup, proving the seq_cst StoreLoad fence is both necessary
(weaker combos stay reachable) and sufficient.

This is the poor-man's, herd7-native form of memory-model litmus synthesis;
Memalloy (Wickerson et al, POPL'17) is the heavyweight Alloy-based tool that
*searches* for distinguishing tests rather than enumerating a known template --
see README.md for wiring it in when Alloy is available.

House style: .format(), no f-strings.
"""
import os
import sys

STORE = {"relaxed": "memory_order_relaxed", "release": "memory_order_release"}
LOAD = {"relaxed": "memory_order_relaxed", "acquire": "memory_order_acquire"}
FENCE = {
    "nofence": "",
    "relfence": "  atomic_thread_fence(memory_order_release);\n",
    "scfence": "  atomic_thread_fence(memory_order_seq_cst);\n",
}

TEMPLATE = """C parkwake_sweep_{tag}
(* AUTO-GENERATED by gen_sweep.py -- park/wake SB shape.
   store={store} load={load} fence={fence}.  exists reachable => lost wakeup. *)
{{
  wake_pending = 0;
  parked_safe = 0;
}}

P0 (atomic_int *parked_safe, atomic_int *wake_pending) {{
  atomic_store_explicit(parked_safe, 1, {store_mo});
{fence_line}  int wp = atomic_load_explicit(wake_pending, {load_mo});
}}

P1 (atomic_int *parked_safe, atomic_int *wake_pending) {{
  atomic_store_explicit(wake_pending, 1, {store_mo});
{fence_line}  int ps = atomic_load_explicit(parked_safe, {load_mo});
}}

exists (0:wp=0 /\\ 1:ps=0)
"""


def variants():
    for store in ("relaxed", "release"):
        for load in ("relaxed", "acquire"):
            for fence in ("nofence", "relfence", "scfence"):
                yield store, load, fence


def render(store, load, fence):
    tag = "{}_{}_{}".format(store, load, fence)
    return tag, TEMPLATE.format(
        tag=tag, store=store, load=load, fence=fence,
        store_mo=STORE[store], load_mo=LOAD[load], fence_line=FENCE[fence])


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "generated")
    if not os.path.isdir(out):
        os.makedirs(out)
    names = []
    for store, load, fence in variants():
        tag, text = render(store, load, fence)
        path = os.path.join(out, "parkwake_sweep_" + tag + ".litmus")
        with open(path, "w") as f:
            f.write(text)
        names.append(tag)
    sys.stdout.write("generated {} litmus variants in {}\n".format(len(names), out))
    for n in names:
        sys.stdout.write("  parkwake_sweep_{}.litmus\n".format(n))


if __name__ == "__main__":
    main()
