\* GENERATED by tools/mn_trace_conform.py from a real RUNLOOM_MN_EVENTS run.
\* Replays the recorded baton transitions through RunloomMNControl's OWN actions
\* under TLC: conformance = each event is an enabled model step and
\* MutualExclusion / BatonConsistent / DeterministicGrant hold.  DO NOT EDIT.
-------------------------- MODULE RunloomMNControlTrace --------------------------
EXTENDS RunloomMNControl, Sequences, Naturals

TraceEvents == << [a |-> "Arrive", h |-> "h2"],
                  [a |-> "Rendezvous", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h1"],
                  [a |-> "Rendezvous", h |-> "h1"],
                  [a |-> "Arrive", h |-> "h3"],
                  [a |-> "Rendezvous", h |-> "h3"],
                  [a |-> "Grant", h |-> "h1"],
                  [a |-> "Arrive", h |-> "h1"],
                  [a |-> "Rendezvous", h |-> "h1"],
                  [a |-> "Grant", h |-> "h1"],
                  [a |-> "Release", h |-> "h1"],
                  [a |-> "Grant", h |-> "h3"],
                  [a |-> "Release", h |-> "h3"],
                  [a |-> "Grant", h |-> "h2"],
                  [a |-> "Release", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h2"],
                  [a |-> "Rendezvous", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h1"],
                  [a |-> "Rendezvous", h |-> "h1"],
                  [a |-> "Arrive", h |-> "h3"],
                  [a |-> "Rendezvous", h |-> "h3"],
                  [a |-> "Grant", h |-> "h2"],
                  [a |-> "Release", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h2"],
                  [a |-> "Rendezvous", h |-> "h2"],
                  [a |-> "Grant", h |-> "h2"],
                  [a |-> "Release", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h2"],
                  [a |-> "Rendezvous", h |-> "h2"],
                  [a |-> "Grant", h |-> "h2"],
                  [a |-> "Release", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h2"],
                  [a |-> "Rendezvous", h |-> "h2"],
                  [a |-> "Grant", h |-> "h1"],
                  [a |-> "Release", h |-> "h1"],
                  [a |-> "Arrive", h |-> "h1"],
                  [a |-> "Rendezvous", h |-> "h1"],
                  [a |-> "Grant", h |-> "h1"],
                  [a |-> "Release", h |-> "h1"],
                  [a |-> "Grant", h |-> "h3"],
                  [a |-> "Release", h |-> "h3"],
                  [a |-> "Grant", h |-> "h2"],
                  [a |-> "Release", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h2"],
                  [a |-> "Rendezvous", h |-> "h2"],
                  [a |-> "Arrive", h |-> "h3"],
                  [a |-> "Rendezvous", h |-> "h3"],
                  [a |-> "Arrive", h |-> "h1"],
                  [a |-> "Rendezvous", h |-> "h1"],
                  [a |-> "Grant", h |-> "h2"],
                  [a |-> "Release", h |-> "h2"],
                  [a |-> "Grant", h |-> "h1"],
                  [a |-> "Release", h |-> "h1"],
                  [a |-> "Arrive", h |-> "h1"],
                  [a |-> "Rendezvous", h |-> "h1"],
                  [a |-> "Grant", h |-> "h3"],
                  [a |-> "Release", h |-> "h3"],
                  [a |-> "Grant", h |-> "h1"],
                  [a |-> "Release", h |-> "h1"] >>

VARIABLE tpc

TInit == Init /\ tpc = 1

TNext ==
    \/ /\ tpc <= Len(TraceEvents)
       /\ LET e == TraceEvents[tpc] IN
            /\ \/ (e.a = "Arrive"     /\ Arrive(e.h))
               \/ (e.a = "Rendezvous" /\ Rendezvous(e.h))
               \/ (e.a = "Grant"      /\ Grant(e.h))
               \/ (e.a = "Release"    /\ Release(e.h))
            /\ tpc' = tpc + 1
    \/ /\ tpc > Len(TraceEvents)
       /\ UNCHANGED <<vars, tpc>>

TSpec == TInit /\ [][TNext]_<<vars, tpc>>
=============================================================================
