\* GENERATED by tools/tla_trace_conform.py from a real RUNLOOM_GILSTATE_TRACE run.
\* Replays the recorded hub-tstate lifecycle events through RunloomGilstate's OWN
\* Create / DoDelete actions under TLC: conformance = each event is an enabled
\* model step and the invariants hold.  DO NOT EDIT (regenerated per run).
---------------------------- MODULE RunloomGilstateTrace ----------------------------
EXTENDS RunloomGilstate, Sequences, Naturals

TraceEvents == << [a |-> "Create", h |-> "h1", d |-> "h1"],
                  [a |-> "Create", h |-> "h2", d |-> "h2"],
                  [a |-> "Create", h |-> "h3", d |-> "h3"],
                  [a |-> "Create", h |-> "r1", d |-> "r1"],
                  [a |-> "Create", h |-> "r2", d |-> "r2"],
                  [a |-> "Create", h |-> "r3", d |-> "r3"],
                  [a |-> "Delete", h |-> "r1", d |-> "main"],
                  [a |-> "Delete", h |-> "r2", d |-> "main"],
                  [a |-> "Delete", h |-> "r3", d |-> "main"],
                  [a |-> "Delete", h |-> "h1", d |-> "main"],
                  [a |-> "Delete", h |-> "h2", d |-> "main"],
                  [a |-> "Delete", h |-> "h3", d |-> "main"] >>

VARIABLE tpc

TInit == Init /\ tpc = 1

TNext ==
    \/ /\ tpc <= Len(TraceEvents)
       /\ LET e == TraceEvents[tpc] IN
            /\ \/ (e.a = "Create" /\ Create(e.h))
               \/ (e.a = "Delete" /\ DoDelete(e.h, e.d))
            /\ tpc' = tpc + 1
    \/ /\ tpc > Len(TraceEvents)
       /\ UNCHANGED <<vars, tpc>>

TSpec == TInit /\ [][TNext]_<<vars, tpc>>
=============================================================================
