\* GENERATED by tools/stw_trace_conform.py from a real RUNLOOM_STW_TRACE run.
\* Replays the recorded CPython stop-the-world (M1+M2) transitions through
\* RunloomCPythonSTW's OWN actions under TLC.  DO NOT EDIT (regenerated per run).
\*
\* PRESENCE: a real run churns -- transient tstates (rescue tstates, short-lived
\* native threads at recycled addresses) come and go, so not every id is co-present.
\* This module adds a `present` set (the live tstates) driven by Create/Destroy that
\* the tool injects from each id's first/last appearance, and quantifies STW
\* completion + STWExclusive over PRESENT hubs only.  The base RunloomCPythonSTW
\* model is untouched -- so its 4 gated checks (correct/bug/live/livebug) are
\* unaffected; only this generated driver knows about presence.
-------------------------- MODULE RunloomCPythonSTWTrace --------------------------
EXTENDS RunloomCPythonSTW, Sequences, Naturals, TLC

TraceEvents == << [a |-> "GCRequest", h |-> "h2"],
                  [a |-> "GCPark", h |-> "h5"],
                  [a |-> "Attach", h |-> "h4"],
                  [a |-> "Attach", h |-> "h3"],
                  [a |-> "GCPark", h |-> "h6"],
                  [a |-> "GCPark", h |-> "h7"],
                  [a |-> "GCPark", h |-> "h1"],
                  [a |-> "SelfSuspend", h |-> "h3"],
                  [a |-> "SelfSuspend", h |-> "h4"],
                  [a |-> "GCStopComplete", h |-> "h2"],
                  [a |-> "GCStart", h |-> "h2"] >>

VARIABLE tpc, present

\* A tstate enters the thread list (a fresh PyThreadState, detached) ...
TCreate(h) ==
    /\ h \notin present
    /\ present' = present \cup {h}
    /\ state' = [state EXCEPT ![h] = "detached"]
    /\ UNCHANGED <<world, requester, stops, wedged>>

\* ... and leaves it (deleted while detached, never the requester, never mid-stop).
TDestroy(h) ==
    /\ h \in present
    /\ h # requester
    /\ state[h] = "detached"
    /\ present' = present \ {h}
    /\ UNCHANGED <<state, world, requester, stops, wedged>>

\* stop_the_world completes once every PRESENT other hub is suspended (a not-present
\* tstate is not in the interpreter's thread list, so the requester never waits on it).
TGCStopComplete ==
    /\ world = "stopping"
    /\ \A h \in (present \ {requester}) : state[h] = "suspended"
    /\ world' = "stopped"
    /\ UNCHANGED <<state, requester, stops, wedged, present>>

\* Init reconstructed from the window start: per-hub state from the prefix replay;
\* `present` is exactly the tstates alive at the start; no STW in flight.
TInit ==
    /\ state = (("h1" :> "detached") @@ ("h2" :> "attached") @@ ("h3" :> "attached") @@ ("h4" :> "detached") @@ ("h5" :> "detached") @@ ("h6" :> "detached") @@ ("h7" :> "detached"))
    /\ world = "running"
    /\ requester = NoHub
    /\ stops = 0
    /\ wedged = [h \in Hubs |-> FALSE]
    /\ tpc = 1
    /\ present = {"h1", "h2", "h3", "h4", "h5", "h6", "h7"}

TNext ==
    \/ /\ tpc <= Len(TraceEvents)
       /\ LET e == TraceEvents[tpc] IN
            /\ \/ (e.a = "Attach"         /\ Attach(e.h)        /\ UNCHANGED present)
               \/ (e.a = "Detach" /\ e.h # requester /\ Detach(e.h) /\ UNCHANGED present)
               \/ (e.a = "Detach" /\ e.h = requester /\ RequesterPause(e.h) /\ UNCHANGED present)
               \/ (e.a = "GCRequest" /\ e.h = "ext" /\ GCRequestExt /\ UNCHANGED present)
               \/ (e.a = "GCRequest" /\ e.h # "ext" /\ GCRequest(e.h) /\ UNCHANGED present)
               \/ (e.a = "GCPark"         /\ GCPark(e.h)       /\ UNCHANGED present)
               \/ (e.a = "SelfSuspend"    /\ SelfSuspend(e.h)  /\ UNCHANGED present)
               \/ (e.a = "GCStopComplete" /\ TGCStopComplete)
               \/ (e.a = "GCStart"        /\ GCStart           /\ UNCHANGED present)
               \/ (e.a = "Create"         /\ TCreate(e.h))
               \/ (e.a = "Destroy"        /\ TDestroy(e.h))
            /\ tpc' = tpc + 1
    \/ /\ tpc > Len(TraceEvents)
       /\ UNCHANGED <<vars, tpc, present>>

\* present-aware safety + typing (checked instead of the base model's, which
\* quantify over ALL Hubs and would wrongly demand a departed tstate be suspended).
TPresentOK == present \subseteq Hubs
TSTWExclusive ==
    (world = "stopped") => \A h \in (present \ {requester}) : state[h] = "suspended"
TRequesterAttached ==
    (world = "stopped" /\ requester # External)
        => (requester \in present /\ state[requester] = "attached")

TSpec == TInit /\ [][TNext]_<<vars, tpc, present>>
=============================================================================
