#!/usr/bin/env python3
"""mn_trace_conform.py -- TRACE CONFORMANCE for the controlled-baton scheduler:
run RunloomMNControl.tla against the ACTUAL extension.

The baton emits its protocol transitions (RUNLOOM_MN_EVENTS=<path>: Arrive /
Rendezvous / Grant / Release, one ndjson line each).  This turns that real trace
into a generated RunloomMNControlTrace.tla that EXTENDS RunloomMNControl and
drives its OWN Arrive / Rendezvous / Grant / Release actions in the recorded
order, then TLC checks MutualExclusion + BatonConsistent + DeterministicGrant
hold at every step.  No re-transcription: TLC checks the actual run against the
actual verified baton model.

  - a real controlled-scheduler run conforms (every event is an enabled model
    step; at most one hub ever holds the baton);
  - drop a Release from the trace and the next Grant can no longer fire
    (current != NoHub) -> TLC deadlocks: the model rejects the double-hold that
    MutualExclusion forbids.

Every baton event is logged (the acquire/grant/release points all sit under the
controller lock, so the trace is a faithful total order), so the trace drives the
model directly -- no hidden-action search.  House style: .format(), no f-strings.

Usage: mn_trace_conform.py <events.ndjson>
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TLA = os.path.join(ROOT, "verify", "tla")
JAR = os.path.join(TLA, "tla2tools.jar")


def hub_name(i):
    return "h{}".format(int(i) + 1)         # hub id 0 -> h1


def load_events(path):
    out = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                out.append(json.loads(line))
    return out


TEMPLATE = '''\\* GENERATED by tools/mn_trace_conform.py from a real RUNLOOM_MN_EVENTS run.
\\* Replays the recorded baton transitions through RunloomMNControl's OWN actions
\\* under TLC: conformance = each event is an enabled model step and
\\* MutualExclusion / BatonConsistent / DeterministicGrant hold.  DO NOT EDIT.
-------------------------- MODULE RunloomMNControlTrace --------------------------
EXTENDS RunloomMNControl, Sequences, Naturals

TraceEvents == << {seq} >>

VARIABLE tpc

TInit == Init /\\ tpc = 1

TNext ==
    \\/ /\\ tpc <= Len(TraceEvents)
       /\\ LET e == TraceEvents[tpc] IN
            /\\ \\/ (e.a = "Arrive"     /\\ Arrive(e.h))
               \\/ (e.a = "Rendezvous" /\\ Rendezvous(e.h))
               \\/ (e.a = "Grant"      /\\ Grant(e.h))
               \\/ (e.a = "Release"    /\\ Release(e.h))
            /\\ tpc' = tpc + 1
    \\/ /\\ tpc > Len(TraceEvents)
       /\\ UNCHANGED <<vars, tpc>>

TSpec == TInit /\\ [][TNext]_<<vars, tpc>>
=============================================================================
'''

CFG = '''\\* GENERATED.  MaxRuns >= the max Grants-to-any-hub in the trace (each Grant+Release
\\* is one run; Arrive needs runs < MaxRuns).  Timers off (the workload has none).
CONSTANTS
    Hubs = {{{hubs}}}
    NoHub = NoHub
    Preempt = TRUE
    Barrier = TRUE
    Timers = FALSE
    LogicalClock = TRUE
    MaxClock = 0
    MaxRuns = {maxruns}
SPECIFICATION TSpec
INVARIANT TypeOK
INVARIANT MutualExclusion
INVARIANT BatonConsistent
INVARIANT DeterministicGrant
'''


def main():
    if len(sys.argv) < 2:
        print("usage: mn_trace_conform.py <events.ndjson>")
        return 2
    events = load_events(sys.argv[1])
    if not events:
        print("empty trace (was RUNLOOM_MN_EVENTS set, with RUNLOOM_MN_SEED?)")
        return 2
    hubs = sorted({hub_name(e["h"]) for e in events})
    grants = {}
    for e in events:
        if e["a"] == "Grant":
            grants[hub_name(e["h"])] = grants.get(hub_name(e["h"]), 0) + 1
    maxruns = max(grants.values()) if grants else 1

    seq = ",\n                  ".join(
        '[a |-> "{}", h |-> "{}"]'.format(e["a"], hub_name(e["h"])) for e in events)
    with open(os.path.join(TLA, "RunloomMNControlTrace.tla"), "w") as f:
        f.write(TEMPLATE.format(seq=seq))
    with open(os.path.join(TLA, "RunloomMNControlTrace.cfg"), "w") as f:
        f.write(CFG.format(hubs=", ".join('"{}"'.format(h) for h in hubs),
                           maxruns=maxruns))

    if not os.path.exists(JAR):
        print("tla2tools.jar missing; run verify/tla/run_tla.sh once")
        return 2
    meta = "/tmp/runloom_mntrace_{}".format(os.getpid())
    proc = subprocess.run(
        ["java", "-cp", JAR, "tlc2.TLC", "-metadir", meta,
         "-config", "RunloomMNControlTrace.cfg", "RunloomMNControlTrace.tla"],
        cwd=TLA, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    out = proc.stdout
    print("  events: {}   hubs: {}   MaxRuns: {}".format(len(events), ", ".join(hubs), maxruns))
    if "No error has been found" in out:
        print("  CONFORMS -- every baton event is a legal RunloomMNControl step; "
              "MutualExclusion + BatonConsistent + DeterministicGrant hold")
        return 0
    if "is violated" in out:
        inv = next((l.strip() for l in out.splitlines() if "is violated" in l), "an invariant")
        print("  NON-CONFORMING -- {}".format(inv))
        return 1
    if "Deadlock" in out or "deadlock" in out:
        print("  NON-CONFORMING -- a recorded event was not an enabled model step "
              "(e.g. a Grant with the baton still held: the double-hold "
              "MutualExclusion forbids)")
        return 1
    print("  TLC error:\n" + "\n".join(out.splitlines()[-10:]))
    return 2


if __name__ == "__main__":
    sys.exit(main())
