#!/usr/bin/env python3
"""tla_trace_conform.py -- TRACE CONFORMANCE: run a TLA+ model against the ACTUAL
extension.

A formal model (verify/tla/RunloomGilstate.tla) is only as trustworthy as its
correspondence to the C code -- TLC checks the model, not the binary.  This
closes that gap for the gilstate-TSS lifecycle (M4 / contract C6): the real
extension emits a trace of its hub-tstate create/delete events
(RUNLOOM_GILSTATE_TRACE=<path>, one ndjson line each), and this tool replays that
trace through the model's OWN actions under TLC.  No re-transcription: the
generated RunloomGilstateTrace.tla EXTENDS RunloomGilstate and drives its real
Create / DoDelete operators, so TLC is checking the actual run against the actual
spec.  Conformance = every logged event is an enabled model step AND the model
invariants (GilstateContract, GilBindingConsistent) hold at each one.

  - a fixed-code run (hubs delete their own tstate) conforms;
  - a run with RUNLOOM_GILSTATE_DELETE_ON_MAIN=1 (the pre-c28e5ca bug) emits a
    Delete with deleter=main, and TLC flags GilstateContract violated -- the same
    bad state the RunloomGilstate_bug.cfg negative control reaches.

House style: .format(), no f-strings.

Usage: tla_trace_conform.py <trace.ndjson>
"""
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TLA = os.path.join(ROOT, "verify", "tla")
JAR = os.path.join(TLA, "tla2tools.jar")


RESCUE_BASE = 1000   # rescue tstates are traced in a disjoint id band (>= 1000)
                     # so the model treats them as their own threads, not re-
                     # created hubs -- mirror of RUNLOOM_GILSTATE_RESCUE_TRACE_ID
                     # in src/runloom_c/mn_sched_handoff.c.inc.


def hub_name(i):
    i = int(i)
    if i >= RESCUE_BASE:
        return "r{}".format(i - RESCUE_BASE + 1)   # rescue-thread tstate (own thread)
    return "h{}".format(i + 1)                      # hub id 0 -> h1 (matches the .cfg's Hubs)


def thread_name(d):
    return "main" if int(d) == -1 else hub_name(int(d))


def load_events(path):
    events = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            e = json.loads(line)
            events.append(e)
    return events


def to_tla_record(e):
    # Create(h) ignores d in the model, but carrying it is harmless and uniform.
    return '[a |-> "{}", h |-> "{}", d |-> "{}"]'.format(
        e["a"], hub_name(e["h"]), thread_name(e["d"]))


def gen_spec(events):
    seq = ",\n                  ".join(to_tla_record(e) for e in events)
    return TEMPLATE.format(seq=seq)


TEMPLATE = '''\\* GENERATED by tools/tla_trace_conform.py from a real RUNLOOM_GILSTATE_TRACE run.
\\* Replays the recorded hub-tstate lifecycle events through RunloomGilstate's OWN
\\* Create / DoDelete actions under TLC: conformance = each event is an enabled
\\* model step and the invariants hold.  DO NOT EDIT (regenerated per run).
---------------------------- MODULE RunloomGilstateTrace ----------------------------
EXTENDS RunloomGilstate, Sequences, Naturals

TraceEvents == << {seq} >>

VARIABLE tpc

TInit == Init /\\ tpc = 1

TNext ==
    \\/ /\\ tpc <= Len(TraceEvents)
       /\\ LET e == TraceEvents[tpc] IN
            /\\ \\/ (e.a = "Create" /\\ Create(e.h))
               \\/ (e.a = "Delete" /\\ DoDelete(e.h, e.d))
            /\\ tpc' = tpc + 1
    \\/ /\\ tpc > Len(TraceEvents)
       /\\ UNCHANGED <<vars, tpc>>

TSpec == TInit /\\ [][TNext]_<<vars, tpc>>
=============================================================================
'''

CFG = '''\\* GENERATED. Hubs must cover the trace's hub ids; DeleteOnOwner is unused on the
\\* trace path (DoDelete is driven directly by the recorded events).
CONSTANTS
    Hubs = {{{hubs}}}
    DeleteOnOwner = TRUE
SPECIFICATION TSpec
INVARIANT TypeOK
INVARIANT GilstateContract
INVARIANT GilBindingConsistent
'''


def main():
    if len(sys.argv) < 2:
        print("usage: tla_trace_conform.py <trace.ndjson>")
        return 2
    events = load_events(sys.argv[1])
    if not events:
        print("empty trace -- nothing to check (was RUNLOOM_GILSTATE_TRACE set?)")
        return 2
    hubs = sorted({hub_name(e["h"]) for e in events})
    spec_path = os.path.join(TLA, "RunloomGilstateTrace.tla")
    cfg_path = os.path.join(TLA, "RunloomGilstateTrace.cfg")
    with open(spec_path, "w") as f:
        f.write(gen_spec(events))
    with open(cfg_path, "w") as f:
        # Hubs as STRING values (the trace records + the model's Main="main" are
        # strings); a model-value {h1,h2} would not equal the "h1" string records.
        f.write(CFG.format(hubs=", ".join('"{}"'.format(h) for h in hubs)))

    if not os.path.exists(JAR):
        print("tla2tools.jar missing at {}; run verify/tla/run_tla.sh once".format(JAR))
        return 2
    meta = "/tmp/runloom_traceconf_{}".format(os.getpid())
    proc = subprocess.run(
        ["java", "-Xmx1g", "-cp", JAR, "tlc2.TLC", "-workers", "4", "-metadir", meta,
         "-config", "RunloomGilstateTrace.cfg", "RunloomGilstateTrace.tla"],
        cwd=TLA, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    out = proc.stdout
    print("  events: {}   hubs: {}".format(len(events), ", ".join(hubs)))
    if "No error has been found" in out:
        print("  CONFORMS -- every logged event is a legal RunloomGilstate step; "
              "invariants hold")
        return 0
    if "is violated" in out:
        inv = "an invariant"
        for line in out.splitlines():
            if "is violated" in line:
                inv = line.strip()
                break
        print("  NON-CONFORMING -- {}".format(inv))
        print("  (the real run drove the model into a bad state -- e.g. a hub "
              "tstate deleted from the wrong thread)")
        return 1
    if "Deadlock" in out or "deadlock" in out:
        print("  NON-CONFORMING -- the recorded event sequence is not possible in "
              "the model (an action was not enabled when it was logged)")
        return 1
    print("  TLC error:\n" + "\n".join(out.splitlines()[-8:]))
    return 2


if __name__ == "__main__":
    sys.exit(main())
